// ui
export const UI_NAVIGATION_HIDE = 'UI_NAVIGATION_HIDE';
export const UI_NAVIGATION_SHOW = 'UI_NAVIGATION_SHOW';
export const UI_NAVIGATION_TOGGLE = 'UI_NAVIGATION_TOGGLE';
export const UI_NAVIGATION_AUTO = 'UI_NAVIGATION_AUTO';
